(function(){
	var ee = new ExtensionInterface();
	var delegate = function(character, action, options) {
		if (!ee || !ee.gameDelegate || !ee.notifyUpdate)
			return 255;
		switch (action) {
			case "Cancel":
				ee.notifyUpdate({"Cancel":null});
				break;
			case "GameAction":
				switch (options["Action"]) {
					case "Move":
						ee.setCharacterPosition(character, ee.getSelectedGrid());
						ee.notifyUpdate({"Characters":"ALL"});
						break;
					case "NextRound":
						ee.notifyUpdate({
							"Dialog" : "Message",
							"Message" : "You need to wait for your round now. \nThis prompt is generated by this Javascript"
						});
						break;
				}
				break;
		}
		return 0;
	};
	ee.gameDelegate = delegate;
	var d = ee.notifyUpdate;
})();